services:
  app:
    platform: linux/amd64
    container_name: app
    build:
      context: ./app/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 9323:9323
    volumes:
      - ./:/workspace
      - /workspace/app/node_modules
      - /workspace/app/.next
      - /workspace/app/.swc
    environment:
      TZ: Asia/Tokyo
      AUTH_SECRET: "cEPKRUHbWS2ylvvhPc+Mdbr1pPAmt1Ky0qxJVGdhXp0="
      API_URL: "http://api:8000/api"

  api:
    platform: linux/amd64
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile.api
    depends_on:
      - postgres
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./:/workspace
      - /workspace/api/.venv
    environment:
      TZ: Asia/Tokyo
      PYTHONDONTWRITEBYTECODE: "1"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_PASSWORD: "password"
      DB_NAME: "postgres"
      JWT_SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      JWT_ALGORITHM: "HS256"
      JWT_EXPIRE_MINUTES: 15
      REFRESH_JWT_SECRET_KEY: "5fc567db2718af3c4461fdc685dc7290c33efbf084111edc04131fbafd254c19"
      REFRESH_JWT_ALGORITHM: "HS256"
      REFRESH_JWT_EXPIRE_DAYS: 90

  postgres:
    platform: linux/amd64
    container_name: postgres
    build:
      context: ./api/
      dockerfile: Dockerfile.database
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"