services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ../:/workspace
      - /workspace/app/node_modules
      - /workspace/app/.next
      - /workspace/app/.swc
    environment:
      AUTH_SECRET: "cEPKRUHbWS2ylvvhPc+Mdbr1pPAmt1Ky0qxJVGdhXp0="
      API_URL: "http://localhost:8000/api"
    network_mode: host