FROM python:3.12

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /workspace/api

COPY ./pyproject.toml ./
COPY ./uv.lock ./
COPY ./.python-version ./

RUN uv sync --frozen

COPY ./app ./app

CMD [".venv/bin/fastapi", "dev", "--host", "0.0.0.0"]
