name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts'
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Install dependencies
        run: npm i
        working-directory: ./app
      - name: Run unit tests
        run: npm run test

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --frozen
        working-directory: ./api
      - name: Run pytest
        run: uv run pytest
        working-directory: ./api