name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run jest
        run: echo "no jest tests configured"

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
        working-directory: ./api
      - name: Run pytest
        run: uv run pytest
        working-directory: ./api